# Generated by Django 5.2.4 on 2025-08-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_rename_apppoint_appoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('address', models.TextField()),
                ('emailuser', models.EmailField(max_length=254)),
            ],
        ),
    ]
