# Generated by Django 5.2.4 on 2025-08-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='emailuser',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phonenumber',
        ),
    ]
